### ISSUE TITLE
NameError: name 'TimModel' is not defined

### ISSUE THREAD

**Issue by shuzhongguo** [Deltares/dfm_tools#313]
Traceback (most recent call last):
  File "G:/1ashuzhongguo/code/PycharmProjects/delft3d_visu/test.py", line 7, in <module>
    import dfm_tools as dfmt
  File "D:\ProgramData\Anaconda3\envs\dfm_tools_env\lib\site-packages\dfm_tools\__init__.py", line 13, in <module>
    from dfm_tools.hydrolib_helpers import *
  File "D:\ProgramData\Anaconda3\envs\dfm_tools_env\lib\site-packages\dfm_tools\hydrolib_helpers.py", line 317, in <module>
    def TimModel_to_DataFrame(data_tim:TimModel, parse_column_labels:bool = True, refdate:(dt.datetime, pd.Timestamp, str, int, float) = None):
NameError: name 'TimModel' is not defined

**Comment by veenstrajelmer** [comment]
This was noticed indeed, and will be solved today or tomorrow.

**Comment by shuzhongguo** [comment]
@veenstrajelmer OK, thanks
